<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'uz' => 'ru',
    'Bosh sahifa' => 'Домой',
    'Darsliklar' => 'Учебники',
    'Biz haqimizda' => 'О нас',
    'Aloqa' => 'Контакты',
    'Chiqish' => 'Выход',
    'Sinflar' => 'Классы',
    'Bo`limlar' => 'Разделы',
    'Yuborish' => 'Отправить',
    'Bekor qilish' => 'Отмена',
    'Yangiliklar' => 'Новости',
    'Batafsil' => 'Больше',
    'Yana yangiliklar' => 'Больше новости',
    'Yana videolar' => 'Больше ролики',
    'Hammasi shular' => 'Вот и все',
    'Baham ko`ring:' => 'Доля:',
    'Til'=>'Язык',
    'Fayl'=>'файл',
    'Rasmlar'=>'Картинки',
    'Kirish'=>'Войти',
    'Ro`yhatdan o`tish'=>'Регистрация',
    'Izohlar' => 'Комментарии',
    'Shaxsiy kabinet' => 'Личный кабинет',
    'Saqlash'=>'Сохранить',
    'Murabbiylar'=>'Тренеры',
    'Biz bilan bog`lanish' => 'Связаться с нами',
    'Manzil'=>'Адрес',
    'Tel:'=>'Тел:',
    'Sizda savollar bormi?'=>'У вас есть вопросы?',
    'Menyu' => "Меню",
    'Bizning takliflar'=> 'Наши предложения',
    'Bizning'=>'Наши',
    'sertifikatlar'=>'сертификаты',
    'Qisqacha'=>'Коротко',
    'Barcha huquqlar himoyalangan!' => 'Все права защищены!',



];
